// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNotes(arg1, arg2) {
  return window['go']['projects']['ProjectsHandler']['CreateNotes'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['projects']['ProjectsHandler']['CreateProject'](arg1);
}

export function EditPersonalNotes(arg1, arg2) {
  return window['go']['projects']['ProjectsHandler']['EditPersonalNotes'](arg1, arg2);
}

export function EditProject(arg1) {
  return window['go']['projects']['ProjectsHandler']['EditProject'](arg1);
}

export function GetAllProjects() {
  return window['go']['projects']['ProjectsHandler']['GetAllProjects']();
}

export function GetChildProjectsByParentID(arg1) {
  return window['go']['projects']['ProjectsHandler']['GetChildProjectsByParentID'](arg1);
}

export function GetNotesByProjectID(arg1) {
  return window['go']['projects']['ProjectsHandler']['GetNotesByProjectID'](arg1);
}

export function GetProjectByID(arg1) {
  return window['go']['projects']['ProjectsHandler']['GetProjectByID'](arg1);
}

export function SearchProjectAssignee(arg1) {
  return window['go']['projects']['ProjectsHandler']['SearchProjectAssignee'](arg1);
}
