// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CreateWebSocketRoom(arg1:number):Promise<void>;

export function DisconnectWebSocketRoom():Promise<void>;

export function GetUser():Promise<types.User>;

export function JoinWebSocketRoom(arg1:number,arg2:number,arg3:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<number>;

export function Logout():Promise<void>;

export function ReadSocketMessage():Promise<void>;

export function Register(arg1:types.RegisterReq):Promise<void>;

export function SendNotification(arg1:number,arg2:types.Notification):Promise<void>;

export function WriteSocketMessage(arg1:types.SocketMessage):Promise<void>;
