// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWebSocketRoom(arg1) {
  return window['go']['main']['App']['CreateWebSocketRoom'](arg1);
}

export function DisconnectWebSocketRoom() {
  return window['go']['main']['App']['DisconnectWebSocketRoom']();
}

export function GetUser() {
  return window['go']['main']['App']['GetUser']();
}

export function JoinWebSocketRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['JoinWebSocketRoom'](arg1, arg2, arg3);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ReadSocketMessage() {
  return window['go']['main']['App']['ReadSocketMessage']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function WriteSocketMessage(arg1) {
  return window['go']['main']['App']['WriteSocketMessage'](arg1);
}
