// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetUser():Promise<main.User>;

export function JoinWebSocketRoom(arg1:number,arg2:number,arg3:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<number>;

export function Logout():Promise<void>;

export function SendNotification(arg1:number,arg2:main.Notification):Promise<void>;

export function WriteSocketMessage(arg1:main.SocketMessage):Promise<void>;
