// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['ProjectsHandler']['CreateProject'](arg1);
}

export function GetAllProjects() {
  return window['go']['main']['ProjectsHandler']['GetAllProjects']();
}
