// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateProject(arg1:main.ProjectReq):Promise<void>;

export function GetAllProjects():Promise<Array<main.Project>>;
